// Reads BankOfDad.xlsx and writes db/seed.sql.
// Re-run with `npm run db:generate-seed` if the spreadsheet ever changes.
import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import { readSheetCells } from "./parse-xlsx.mjs";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const cells = readSheetCells(join(root, "BankOfDad.xlsx"));

// The sheet is three side-by-side blocks; row 5 holds each kid's name and
// row 6 the headers (Date / Money / Total / Event), so data starts at row 7.
const BLOCKS = [
  { nameCell: "B5", date: "B", amount: "C", total: "D", reason: "E" },
  { nameCell: "G5", date: "G", amount: "H", total: "I", reason: "J" },
  { nameCell: "L5", date: "L", amount: "M", total: "N", reason: "O" },
];
const FIRST_DATA_ROW = 7;
const LAST_DATA_ROW = 500;

const slugify = (s) => s.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "");
const sqlStr = (s) => "'" + String(s).replace(/'/g, "''") + "'";

const kids = [];
const problems = [];

for (const [i, block] of BLOCKS.entries()) {
  const name = cells[block.nameCell];
  if (!name) throw new Error(`No kid name found in ${block.nameCell}`);

  const transactions = [];
  for (let row = FIRST_DATA_ROW; row <= LAST_DATA_ROW; row++) {
    const date = cells[block.date + row];
    const amount = cells[block.amount + row];
    if (date === undefined && amount === undefined) continue;
    if (date === undefined || amount === undefined) {
      problems.push(`${name} row ${row}: missing ${date === undefined ? "date" : "amount"}`);
      continue;
    }
    const reason = String(cells[block.reason + row] ?? "").trim();
    transactions.push({
      row,
      date,
      amount,
      reason,
      // Every interest row in the sheet says so in the Event column
      // ("Interest", "August Interest", "Sept Interest", …).
      kind: /interest/i.test(reason) ? "interest" : "manual",
      sheetTotal: cells[block.total + row],
    });
  }

  // Sanity check 1: our amounts must rebuild the spreadsheet's running total.
  let running = 0;
  for (const t of transactions) {
    running += t.amount;
    if (t.sheetTotal !== undefined && Math.abs(running - t.sheetTotal) > 0.005) {
      problems.push(`${name} row ${t.row}: running ${running} != sheet ${t.sheetTotal}`);
    }
  }

  // Sanity check 2: the DB has a unique index on one interest row per kid per date.
  const interestDates = new Set();
  for (const t of transactions.filter((t) => t.kind === "interest")) {
    if (interestDates.has(t.date)) problems.push(`${name}: two interest rows on ${t.date}`);
    interestDates.add(t.date);
  }

  kids.push({ name, slug: slugify(name), sortOrder: i, transactions, balance: running });
}

if (problems.length) {
  console.error("Spreadsheet import problems:\n  " + problems.join("\n  "));
  process.exit(1);
}

const lines = [
  "-- Generated by scripts/generate-seed.mjs from BankOfDad.xlsx. Do not edit by hand.",
  "-- Historical amounts are kept at full spreadsheet precision; the app rounds to cents from here on.",
  "",
];

for (const kid of kids) {
  lines.push(
    `insert into kids (name, slug, sort_order) values (${sqlStr(kid.name)}, ${sqlStr(kid.slug)}, ${kid.sortOrder})`,
    "  on conflict (slug) do nothing;",
    ""
  );
}

for (const kid of kids) {
  lines.push(`-- ${kid.name}: ${kid.transactions.length} transactions, balance ${kid.balance.toFixed(2)}`);
  lines.push("insert into transactions (kid_id, date, amount, reason, kind) values");
  // Sorted by date so the app's (date, id) ordering matches; a handful of sheet
  // rows were entered out of date order.
  const sorted = [...kid.transactions].sort((a, b) =>
    a.date === b.date ? a.row - b.row : a.date < b.date ? -1 : 1
  );
  const values = sorted.map(
    (t) =>
      `  ((select id from kids where slug = ${sqlStr(kid.slug)}), ${sqlStr(t.date)}, ${t.amount.toFixed(4)}, ${sqlStr(t.reason)}, ${sqlStr(t.kind)})`
  );
  lines.push(values.join(",\n") + ";");
  lines.push("");
}

writeFileSync(join(root, "db", "seed.sql"), lines.join("\n"));

console.log("Wrote db/seed.sql");
for (const kid of kids) {
  const interest = kid.transactions.filter((t) => t.kind === "interest").length;
  console.log(
    `  ${kid.name.padEnd(8)} ${String(kid.transactions.length).padStart(3)} transactions ` +
      `(${interest} interest), balance $${kid.balance.toFixed(2)}`
  );
}
